language: python
python:
  - "3.4"
# command to install dependencies
install:
  - yum install -y postgresql10-server postgresql10 
  - "pip install -r requirements.txt"
# command to run tests
script: 
  - python manage.py test
